defaults: &defaults
  technorati_api_key: xxx
  daylife_access_key: xxx
  daylife_secret: xxx
  twitter_consumer: xxx
  twitter_secret: xxx
  sunlightlabs_key: xxx
  maplight: xxx
  wiki_pass: xxx
  wiki_key: xxx
  wiki_callback_key: xx
  app_key: xxx
  yahoo_apis: xxx
  civicrm_system_key: xxx
  civicrm_user_key: xxx
  project_vote_smart: xxx
  google_maps: xxx
  hoptoad: xxx
  bitly: xxx
  aws_access_key_id: xxx
  aws_secret_access_key: xxx
  formageddon_password: xxx
  formageddon_get_replies_key: xxx
  bing: xxx
  
development:
  <<: *defaults
  
test:
  <<: *defaults

staging:
  <<: *defaults
  
production:
  <<: *defaults
